### ISSUE TITLE
Move this repo to tc39-transfer

### ISSUE THREAD

**Issue by sffc** [tc39-transfer/proposal-intl-duration-format#9]
Since Intl.DurationFormat is at Stage 1, this repo should be moved to the `tc39-transfer` org such that the chairs can move it to `tc39`.

**Comment by ryzokuken** [comment]
@younies can you please do this or give me access to this repo so I could do it? Thanks.

**Comment by younies** [comment]
Thanks @ryzokuken .... I have just transferred it :)
